Update upstream.yml

diff --git a/.github/workflows/upstream.yml b/.github/workflows/upstream.yml
--- a/.github/workflows/upstream.yml
+++ b/.github/workflows/upstream.yml
@@ -1,7 +1,7 @@
 #
 # This is free software, lisence use MIT.
 # 
-# <https://github.com/kiddin9/op-packages>
+# <https://github.com/kiddin9/kwrt-packages>
 #
 name: Merge-upstream
 on:
@@ -86,9 +86,9 @@ jobs:
         git_clone https://github.com/OpenListTeam/OpenList-OpenWRT oplist && mvdir oplist
         git_clone https://github.com/eamonxg/luci-theme-aurora luci-theme-aurora
         git clone --depth 1 -b Fix-mobile-bug https://github.com/whzhni1/luci-app-harbor-file luci-app-harbor-file
-        
         git_sparse_clone master "https://github.com/coolsnowwolf/packages" net/verysync
         git_sparse_clone main "https://github.com/kiddin9/op-packages" luci-app-verysync
+        # 定制 Verysync：菜单路径改为 services，修复打开页面功能
         sed -i 's/{"admin", "nas", "verysync"/{"admin", "services", "verysync"/g' luci-app-verysync/luasrc/controller/verysync.lua
         sed -i 's/\[\[nas\]\]/[[services]]/g' luci-app-verysync/luasrc/view/verysync/verysync_status.htm
         sed -i '/if (data && tb) {/a\\\t\twindow.verysync_port = data.port || 0;' luci-app-verysync/luasrc/view/verysync/verysync_status.htm
@@ -101,8 +101,6 @@ jobs:
           var url = window.location.protocol + "//" + window.location.hostname + ":" + window.verysync_port;\
           window.open(url);\
         }' luci-app-verysync/luasrc/view/verysync/verysync_status.htm
-
-        
         git_sparse_clone main "https://github.com/kiddin9/op-packages" luci-mod-network luci-mod-status luci-mod-system && rm -rf luci-mod-system/htdocs/luci-static/resources/view/system/leds.js && rm -rf luci-mod-system/htdocs/luci-static/resources/view/system/led-trigger/
 
         sed -i '/"admin\/system\/leds": {/,/^	},/d' luci-mod-system/root/usr/share/luci/menu.d/luci-mod-system.json
@@ -255,7 +253,9 @@ jobs:
 
     - name: Apply
       run: |
-        cd $GITHUB_WORKSPACE
+        cd "${GITHUB_WORKSPACE}" || { echo "Failed to cd to GITHUB_WORKSPACE"; exit 1; }
+        pwd
+        ls -la .git || { echo ".git not found"; exit 1; }
         if [ -z "$(git status --porcelain)" ]; then
           echo "✅ No changes to commit, skipping apply."
           exit 0
